# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = ""
language = "javascript"
manifest_version = 3
name = "Geo-IP API at the edge"
service_id = "IbGHHqhlpuFAPXmx5MKzZ3"

[scripts]
  build = "npm exec js-compute-runtime ./src/index.js ./bin/main.wasm"

[local_server.backends.origin_0]
      url = "https://wooden-iris-darkness-glitch.me"

[setup.backends.origin_0]
address = "wooden-iris-darkness-glitch.me"
port = 443
